config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  devise_scope :user do
    get "/users/profile" => "users/sessions#show"
  end

  devise_scope :user do
    put "/users/profile" => "users/sessions#update"
  end

  resources :pets do
    member do
      put "report"
      put "block"
      put "unblock"
      put "block_owner"
      put "unblock_owner"
    end
    collection do
      get "top"
      get "reported"
      get "reported_users"
      get "reported_questions"
      post "block_owner_publications"
      post "unblock_owner_publications"
    end

    resources :images, only: [:show, :create, :destroy]
    resources :adoption_requests, only: [:index, :create] do
      post "accept", on: :member
    end
    resources :questions, only: [:index, :show, :create] do
      member do
        post "answer"
        put "report"
        put "block"
        put "unblock"
      end
    end
  end

  resources :reports, only: [:index]
  root "reports#index"
end

app/models/pet.rb
class Pet < ActiveRecord::Base

  belongs_to :user
  validates :user, presence: true

  has_many :images, class_name: PetImage
  has_many :videos, class_name: PetVideo
  has_many :questions, class_name: PetQuestion
  has_many :adoption_requests

  # validates_format_of :location, with: /[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?),\s*[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)/, if: :location?

  %w[male female].each do |gender|
    const_set "gender_#{gender}".upcase, gender
  end

  GENDERS = [GENDER_MALE, GENDER_FEMALE]
  validates_inclusion_of :gender, in: GENDERS, allow_blank: false

  %w[adoption lost found].each do |publication_type|
    const_set "PUBLICATION_TYPE_#{publication_type}".upcase, publication_type
  end

  LOST_AND_FOUND    = [PUBLICATION_TYPE_LOST, PUBLICATION_TYPE_FOUND]
  PUBLICATION_TYPES = [PUBLICATION_TYPE_ADOPTION] + LOST_AND_FOUND
  validates_inclusion_of :publication_type, in: PUBLICATION_TYPES, allow_blank: true

  TYPES = ["Dog", "Cat"]
  validates_inclusion_of :type, in: TYPES, allow_blank: false

  before_save :update_metadata

  scope :published, -> { where(published: true) }
  scope :reported,  -> { where(reported: true) }
  scope :unblocked, -> { where(blocked: false) }
  scope :males, ->     { where(gender: GENDER_MALE) }
  scope :females, ->   { where(gender: GENDER_FEMALE) }

  scope :near_location, ->(location, max_meters) {
    location_ary = location.split(",").map(&:to_f)

    ids = where.not(location: [nil, ""]).select { |pet| pet.distance_to(location_ary) <= max_meters }.map(&:id)
    where(id: ids)
  }

  scope :with_colors, ->(colors) { field_matches_any(:colors, colors) }
  scope :with_metadata, ->(tags) { field_matches_any(:metadata, tags) }

  scope :approved, -> { includes(:adoption_requests).where(adoption_requests: { approved: true }) }
  scope :lost, -> { where(publication_type: PUBLICATION_TYPE_LOST) }
  scope :found, -> { where(publication_type: PUBLICATION_TYPE_FOUND) }
  scope :for_adoption, -> { where(publication_type: PUBLICATION_TYPE_ADOPTION) }

  def publish
    self.published = true
  end

  def publish!
    self.publish
    self.save!
  end

  def unpublish
    self.published = false
  end

  def unpublish!
    self.unpublish
    self.save!
  end

  def report
    self.reported = true
  end

  def report!
    self.report
    self.save!
  end

  def block
    self.blocked = true
  end

  def block!
    self.block
    self.unpublish
    self.save!
  end

  def unblock
    self.blocked = false
  end

  def unblock!
    self.unblock
    self.publish
    self.save!
  end

  def blocked?
    self.blocked == true
  end

  def metadata_matches(values)
    values.split.count { |tag| self.metadata.include?(tag) }
  end

  def distance_to(other_location)
    loc1 = self.location.split(",").map(&:to_f)
    loc2 = other_location

    rad_per_deg = Math::PI/180 # PI / 180
    rkm = 6371 # Earth radius in kilometers
    rm = rkm * 1000 # Radius in meters

    dlat_rad = (loc2[0] - loc1[0]) * rad_per_deg # Delta, converted to rad
    dlon_rad = (loc2[1] - loc1[1]) * rad_per_deg

    lat1_rad, lon1_rad = loc1.map { |i| i * rad_per_deg }
    lat2_rad, lon2_rad = loc2.map { |i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))

    rm * c # Delta in meters
  end

  private

  def self.to_queries(query)
    query.to_s.strip.split.map { |w| "%#{w.downcase}%" }
  end

  def self.field_matches_any(field, values)
    full_query = nil

    to_queries(values).each do |query|
      field_match = arel_table[field].matches(query)
      full_query  = full_query ? full_query.or(field_match) : field_match
    end

    where(full_query)
  end

  def update_metadata
    tags = []

    # Tag pet based on type, gender and colors.
    %w[type gender].each do |attribute|
      attribute = attribute.to_sym
      tags << I18n.t("pets.#{self.send(attribute).downcase}") if self.send(attribute)
    end
    tags = tags.concat self.colors.split unless self.colors.blank?
    tags = tags.concat self.description.split unless self.description.blank?

    # Merge with existing tags.
    new_meta = tags.compact.map(&:downcase)
    existing_meta = self.metadata.split(" ")

    self.metadata = new_meta.concat(existing_meta).uniq.join(" ")
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy, :report, :block, :unblock, :block_owner, :unblock_owner]

  # GET /pets
  # GET /pets.json
  def index
    pets = pets_from_query

    respond_to do |format|
      format.html do
        @pets = pets.paginate(page: params[:page], per_page: 10)
      end
      format.json do
        @pets = pets
      end
    end
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
    @pet_image = @pet.images.new
  end

  # POST /pets
  # POST /pets.json
  def create
    pet_response = pet_create_service.call(pet_params)
    lost_pet_match_service.call(pet_response)

    @pet = pet_response

    respond_to do |format|
      if pet_response.success?
        format.html { redirect_to pet_response, notice: I18n.t("pets.show.created") }
        format.json { render :show, status: :created, location: pet_response }
      else
        format.html { render :new }
        format.json { render json: pet_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: I18n.t("pets.show.updated") }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: I18n.t("pets.index.destroyed") }
      format.json { head :no_content }
    end
  end

  def reported
    pets = pets_from_query(Pet.reported, true)

    @pets = pets.paginate(page: params[:page], per_page: 10)
  end

  def reported_users
    users = User.where(reported: true)

    order_by = user_search_params.delete(:order_by) || "id"

    users = users.where(user_search_params)
    users = users.order(order_by => :asc)

    @users = users.paginate(page: params[:page], per_page: 10)
  end

  def reported_questions
    questions = PetQuestion.reported

    @questions = questions.paginate(page: params[:page], per_page: 10)
  end

  # POST /pets/1/report.json
  def report
    @pet.report!
    @pet.user.report!
    head :no_content
  end

  # POST /pets/1/block.json
  def block
    @pet.block!

    respond_to do |format|
      format.html { redirect_to request.referrer, notice: I18n.t("pets.blocked") }
      format.json { head :no_content }
    end
  end

  # POST /pets/1/block.json
  def unblock
    @pet.unblock!

    respond_to do |format|
      format.html { redirect_to request.referrer, notice: I18n.t("pets.unblocked") }
      format.json { head :no_content }
    end
  end

  # POST /pets/1/block_owner.json
  def block_owner
    @pet.user.block!

    respond_to do |format|
      format.html { redirect_to request.referrer, notice: I18n.t("pets.blocked_user") }
      format.json { head :no_content }
    end
  end

  # POST /pets/1/block_owner.json
  def unblock_owner
    @pet.user.unblock!

    respond_to do |format|
      format.html { redirect_to request.referrer, notice: I18n.t("pets.unblocked_user") }
      format.json { head :no_content }
    end
  end

  # POST /pets/block_owner_publications.json
  def block_owner_publications
    User.find(params[:id]).pets.each { |pet| pet.block! }

    respond_to do |format|
      format.html { redirect_to request.referrer, notice: I18n.t("pets.blocked_user_publications") }
      format.json { head :no_content }
    end
  end

  # POST /pets/unblock_owner_publications.json
  def unblock_owner_publications
    User.find(params[:id]).pets.each { |pet| pet.unblock! }

    respond_to do |format|
      format.html { redirect_to request.referrer, notice: I18n.t("pets.unblocked_user_publications") }
      format.json { head :no_content }
    end
  end

  def top
    @pets = Pet.where(:published => true).order(created_at: :desc).limit(5)

    render :index
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pet
    @pet = Pet.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pet_params
    params.require(:pet).
      permit(:type, :name, :description, :gender, :colors, :needs_transit_home, :published, :vaccinated, :location,
             :metadata, :age, :children_friendly, :pet_friendly, :publication_type, videos: [])
  end

  def pet_search_params
    params.
      permit(:type, :name, :description, :gender, :colors, :needs_transit_home, :vaccinated, :published, :user_id,
             :metadata, :location, :age, :limit, :children_friendly, :pet_friendly, :with_adoption_requests,
             :adopted, :adopted_by_me, :requested_by_me, :publication_type, :order_by).
      reject { |_, v| v.blank? }
  end

  def pet_create_service
    @pet_create_service ||= PetCreateService.new(current_user)
  end

  def lost_pet_match_service
    @lost_pet_match_service ||= LostPetMatchService.new
  end

  def pets_from_query(base_pets = nil, override_published = false)
    params = pet_search_params
    limit  = params.delete(:limit)

    color_query    = params.delete(:colors)
    metadata_query = params.delete(:metadata)
    location_query = params.delete(:location)
    adopted        = params.delete(:adopted)
    adopted_by_me  = params.delete(:adopted_by_me)
    requested_by_me  = params.delete(:requested_by_me)
    published  = params.delete(:published)
    order_by  = params.delete(:order_by)

    with_adoption_requests = params.delete(:with_adoption_requests)

    pets = base_pets || Pet
    pets = pets.where(params)
    pets = pets.with_metadata(metadata_query) if metadata_query.present?
    pets = pets.with_colors(color_query) if color_query.present?
    pets = pets.near_location(location_query, params.fetch(:location_range, 5000)) if location_query.present?

    # May return unpublished pets.
    pets = pets.includes(:adoption_requests).where(adoption_requests: { approved: [true, false] }) if with_adoption_requests.present?
    pets = pets.includes(:adoption_requests).where(adoption_requests: { approved: true }) if adopted.present?
    pets = pets.includes(:adoption_requests).where(adoption_requests: { approved: true, user_id: current_user.id }) if adopted_by_me.present?
    pets = pets.includes(:adoption_requests).where(adoption_requests: { user_id: current_user.id }).where(['pets.user_id <> ?', current_user.id]) if requested_by_me.present?

    # Published pets by default.
    unless override_published
      pets = pets.published unless adopted.present? || adopted_by_me.present? || requested_by_me.present? ||
        (published.present? && published == 'false')
    end

    if order_by.present?
      pets = pets.order(order_by => :asc)
    else
      pets = pets.order(created_at: :desc)
    end

    pets = pets.limit(limit) if limit

    pets
  end

  def user_search_params
    params.permit(:order_by, :first_name, :last_name).reject { |_, v| v.blank? }
  end

end

app/helpers/pets_helper.rb
module PetsHelper

  def pet_order_by_options(selected = nil)
    options = %w[id type gender name].map { |attribute| [I18n.t("activerecord.attributes.pet.#{attribute}"), attribute] }
    options_for_select options, selected
  end

  def user_order_by_options(selected = nil)
    options = %w[id first_name last_name].map { |attribute| [I18n.t("activerecord.attributes.user.#{attribute}"), attribute] }
    options_for_select options, selected
  end

  def pet_type_options(selected = nil)
    options = Pet::TYPES.map { |type| [I18n.t("pets.#{type.downcase}"), type] }
    options_for_select options, selected
  end

  def pet_gender_options(selected = nil)
    options = Pet::GENDERS.map { |gender| [I18n.t("pets.#{gender}"), gender] }
    options_for_select options, selected
  end

  def boolean_options(selected = nil)
    options_for_select [[I18n.t("shared.yes_word"), true], [I18n.t("shared.no_word"), false]], selected
  end

end

app/views/pets/_filters.html.haml
= form_tag filter_path, method: :get, class: "form-inline", role: "form" do
  .form-group
    = select_tag :order_by, pet_order_by_options(params[:order_by]), prompt: t(".order_by_prompt") , class: "form-control"
  .form-group
    = select_tag :type, pet_type_options(params[:type]), prompt: t(".type_prompt") , class: "form-control"
  .form-group
    = select_tag :gender, pet_gender_options(params[:gender]), prompt: t(".gender_prompt") , class: "form-control"
  -#- %w[published vaccinated needs_transit_home].each do |attribute|
    .form-group
      = select_tag attribute, boolean_options(params[attribute]), prompt: t(".#{attribute}_prompt") , class: "form-control"
  .form-group
    = text_field_tag :colors, params[:colors], placeholder: t("activerecord.attributes.pet.colors") , class: "form-control"
  .form-group
    = text_field_tag :metadata, params[:metadata], placeholder: t("activerecord.attributes.pet.metadata") , class: "form-control"
  = submit_tag t(".submit"), class: "btn btn-primary"

app/views/pets/_form.html.haml
= form_for @pet, html: { class: "form-horizontal", role: "form" } do |f|
  -if @pet.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@pet.errors.count, "error")} prohibited this pet from being saved:"

      %ul
        - @pet.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :type, class: "col-sm-2 control-label"
    .col-sm-10
      = f.select :type, pet_type_options, { prompt: t("shared.prompt") }, class: "form-control", required: true

  .form-group
    = f.label :gender, class: "col-sm-2 control-label"
    .col-sm-10
      = f.select :gender, pet_gender_options, { prompt: t("shared.prompt") }, class: "form-control", required: true

  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control", required: true

  .form-group
    = f.label :colors, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :colors, class: "form-control"

  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :description, class: "form-control", required: true

  .form-group
    = f.label :metadata, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_area :metadata, class: "form-control"

  - %w[needs_transit_home vaccinated published].each do |attribute|
    .form-group
      .col-sm-offset-2.col-sm-10
        .checkbox
          = f.label attribute do
            = f.check_box attribute
            = t("activerecord.attributes.pet.#{attribute}")

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/pets/_image_form.html.haml
= form_for @pet_image, url: pet_images_path(@pet), multipart: true, class: "form-horizontal", role: "form" do |f|
  .form-group
    = f.label :image, class: "col-sm-2 control-label"
    .col-sm-10
      = f.file_field :image, required: true
      %p.help-block= t(".help")

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-info"

app/views/pets/_user_filters.html.haml
= form_tag filter_path, method: :get, class: "form-inline", role: "form" do
  .form-group
    = select_tag :order_by, user_order_by_options(params[:order_by]), prompt: t(".order_by_prompt") , class: "form-control"
  .form-group
    = text_field_tag :first_name, params[:first_name], placeholder: t("activerecord.attributes.user.first_name") , class: "form-control"
  .form-group
    = text_field_tag :last_name, params[:last_name], placeholder: t("activerecord.attributes.user.last_name") , class: "form-control"
  = submit_tag t(".submit"), class: "btn btn-primary"

app/views/pets/edit.html.haml
.page-header
  = link_to pets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    = t("shared.back")
  = link_to @pet, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    = t("shared.show")
  %h1= t(".title")

= render "form"

%hr

= render "image_form"

app/views/pets/index.html.haml
.page-header
  = link_to new_pet_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    = t(".new_pet")
  %h1= t(".title")

.filters
  = render "filters", filter_path: pets_path

%hr

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th= t("activerecord.attributes.pet.id")
        %th= t("activerecord.attributes.pet.type")
        %th= t("activerecord.attributes.pet.gender")
        %th= t("activerecord.attributes.pet.name")
        %th= t("activerecord.attributes.pet.images")
        %th= t("activerecord.attributes.pet.colors")
        %th(colspan="3")= t("shared.actions")

    %tbody
      - @pets.each do |pet|
        %tr
          %td= pet.id
          %td= t("pets.#{pet.type.downcase}")
          %td= t("pets.#{pet.gender}")
          %td= pet.name
          %td= pet.images.count
          %td
            - unless pet.colors.blank?
              - pet.colors.split.each do |color|
                = color
                .color-box{ style: "background-color: #{color};" }
          %td= link_to t("shared.show"), pet
          %td= link_to t("shared.edit"), edit_pet_path(pet)
          %td= link_to t("shared.destroy"), pet, data: { confirm: t("shared.confirm") }, method: :delete

.pagination-container
  = will_paginate @pets, renderer: BootstrapPagination::Rails

app/views/pets/new.html.haml
.page-header
  = link_to pets_path, class: "btn btn-default" do
    %span.glyphicon.glyphicon-list-alt
    = t("shared.back")
  %h1= t(".title")

= render "form"

app/views/pets/reported.html.haml
.page-header
  %h1= t(".title")

.filters
  = render "filters", filter_path: reported_pets_path

- if @pets.any?
  .table-responsive
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th= t("activerecord.attributes.pet.id")
          %th= t("activerecord.attributes.pet.type")
          %th= t("activerecord.attributes.pet.gender")
          %th= t("activerecord.attributes.pet.name")
          %th(colspan="2")= t("shared.actions")

      %tbody
        - @pets.each do |pet|
          %tr
            %td= pet.id
            %td= t("pets.#{pet.type.downcase}")
            %td= t("pets.#{pet.gender}")
            %td= pet.name
            %td
              = link_to t("shared.show"), pet_path(pet)
            %td
              - if pet.blocked?
                = link_to t("shared.unblock"), unblock_pet_path(pet), data: { confirm: t("shared.confirm") }, method: :put
              - else
                = link_to t("shared.block"), block_pet_path(pet), data: { confirm: t("shared.confirm") }, method: :put

  .pagination-container
    = will_paginate @pets, renderer: BootstrapPagination::Rails

- else
  .alert.alert-info= t(".no_results")

app/views/pets/reported_questions.html.haml
.page-header
  %h1= t(".title")

-#.filters
  = render "user_filters", filter_path: reported_users_pets_path

- if @questions.any?
  .table-responsive
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th= t("activerecord.attributes.question.id")
          %th= t("activerecord.attributes.question.body")
          %th(colspan="2")= t("shared.actions")

      %tbody
        - @questions.each do |question|
          %tr
            %td= question.id
            %td= question.body
            %td= link_to t("shared.show"), pet_path(question.pet)
            %td
              - if question.blocked?
                = link_to t("shared.unblock"), unblock_pet_question_path(question.pet, question), data: { confirm: t("shared.confirm") }, method: :put
              - else
                = link_to t("shared.block"), block_pet_question_path(question.pet, question), data: { confirm: t("shared.confirm") }, method: :put

  .pagination-container
    = will_paginate @questions, renderer: BootstrapPagination::Rails

- else
  .alert.alert-info= t(".no_results")

app/views/pets/reported_users.html.haml
.page-header
  %h1= t(".title")

.filters
  = render "user_filters", filter_path: reported_users_pets_path

- if @users.any?
  .table-responsive
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th= t("activerecord.attributes.user.id")
          %th= t("activerecord.attributes.user.first_name")
          %th= t("activerecord.attributes.user.last_name")
          %th= t(".reported_publications")
          %th(colspan="2")= t("shared.actions")

      %tbody
        - @users.each do |user|
          %tr
            %td= user.id
            %td= user.first_name
            %td= user.last_name
            %td
              - user.pets.reported.unblocked.each do |pet|
                = link_to pet.name, pet_path(pet)
            %td
              - if user.blocked?
                = link_to t("shared.unblock"), unblock_owner_pet_path(user.pets.first), data: { confirm: t("shared.confirm") }, method: :put
              - else
                = link_to t("shared.block"), block_owner_pet_path(user.pets.first), data: { confirm: t("shared.confirm") }, method: :put
            %td
              - if user.pets.all?(&:blocked?)
                = link_to t("shared.unblock_all"), unblock_owner_publications_pets_path(id: user.id), data: { confirm: t("shared.confirm") }, method: :post
              - else
                = link_to t("shared.block_all"), block_owner_publications_pets_path(id: user.id), data: { confirm: t("shared.confirm") }, method: :post

  .pagination-container
    = will_paginate @users, renderer: BootstrapPagination::Rails

- else
  .alert.alert-info= t(".no_results")

app/views/pets/show.html.haml
.page-header
  = link_to :back, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    = t("shared.back")
  -#= link_to edit_pet_path(@pet), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    = t("shared.edit")
  %h1= t(".title")

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %tbody
      - t("activerecord.attributes.pet").each do |attribute, text|
        %tr
          %td
            %b= text
          %td
            - value = @pet.send(attribute.to_sym)
            - if value == true
              = t("shared.yes_word")
            - elsif value == false
              = t("shared.no_word")
            - elsif value.acts_like?(:time)
              = l value, format: :short
            - elsif attribute == :colors
              - value.split.each do |color|
                = color
                .color-box{ style: "background-color: #{color};" }
            - elsif attribute == :images
              = value.count
            - else
              = value

- if @pet.questions.any?
  .questions
    %h2= t(".questions")
    - @pet.questions.each do |question|
      .question{ class: "#{question.reported? && 'reported'} #{question.blocked? && 'blocked'}" }
        - if question.blocked?
          %small= t(".question_blocked")
          %br
        - elsif question.reported?
          %small= t(".question_reported")
          %br
        %strong= question.user.full_name
        %p= question.body
        - if question.answer.present?
          %p.answer= question.answer.body

- if @pet.images.any?
  .photos
    %h2= t(".photos")
    - @pet.images.each do |pet_image|
      %img.img-rounded{ src: asset_url(pet_image.image.url(:medium)) }