config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  devise_scope :user do
    get "/users/profile" => "users/sessions#show"
  end

  devise_scope :user do
    put "/users/profile" => "users/sessions#update"
  end

  resources :pets do
    member do
      put "report"
      put "block"
      put "unblock"
      put "block_owner"
      put "unblock_owner"
    end
    collection do
      get "top"
      get "reported"
      get "reported_users"
      get "reported_questions"
      post "block_owner_publications"
      post "unblock_owner_publications"
    end

    resources :images, only: [:show, :create, :destroy]
    resources :adoption_requests, only: [:index, :create] do
      post "accept", on: :member
    end
    resources :questions, only: [:index, :show, :create] do
      member do
        post "answer"
        put "report"
        put "block"
        put "unblock"
      end
    end
  end

  resources :reports, only: [:index]
  root "reports#index"
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    @data = {}

    pets = Pet.where(created_at: date_range)

    @data[I18n.t("reports.index.published")] = pets.for_adoption.count
    @data[I18n.t("reports.index.adopted")]   = pets.for_adoption.approved.count
    @data[I18n.t("reports.index.lost")]      = pets.lost.count
    @data[I18n.t("reports.index.found")]     = pets.lost.approved.count

    adopted_pets = Pet.for_adoption.approved
    @avg_adoption_time = average_approved_time(adopted_pets)

    found_pets = Pet.lost.approved
    @avg_found_time = average_approved_time(found_pets)

    @adoption_total = Pet.for_adoption.count
    @adopted_total  = Pet.for_adoption.approved.count
    @lost_total     = Pet.lost.count
    @found_total    = Pet.lost.approved.count

  rescue ArgumentError => _e
    flash[:error] = I18n.t("shared.date_error")
  end

  private

  def date_range
    @from = params.fetch(:from, 1.month.ago.to_date.to_s)
    @to   = params.fetch(:to, Date.today.to_s)

    raise ArgumentError.new("Invalid date") if !@from || !@to

    from = Date.parse(@from)
    to   = Date.parse(@to)

    raise ArgumentError.new("Invalid date") if from > to

    [from..to]
  end

  def average_approved_time(pets)
    return 0 if pets.empty?

    time_taken = pets.map { |p| p.adoption_requests.find_by(approved: true).created_at - p.created_at }
    time_taken.inject(&:+).to_f / pets.count
  end

end

app/helpers/reports_helper.rb
module ReportsHelper

  def average_time(seconds)
    time = seconds.round(1)
    return "#{time} #{I18n.t('shared.seconds')}" if time < 60

    time = (time / 60.0).round(1)
    return "#{time} #{I18n.t('shared.minutes')}" if time < 60

    time = (time / 60.0).round(1)
    return "#{time} #{I18n.t('shared.hours')}" if time < 24

    time = (time / 24.0).round(1)
    "#{time} #{I18n.t('shared.days')}"
  end

end

app/views/reports/index.html.haml
.page-header
  %h1= t(".title")

= form_for :report, url: reports_path, method: :GET do
  .row
    .col-xs-3
    .col-xs-2
      = label_tag :from, t(".from"), class: "control-label"
      = text_field_tag :from, @from, date_picker_options
    .col-xs-2
      = label_tag :to, t(".to"), class: "control-label"
      = text_field_tag :to, @to, date_picker_options
    .col-xs-2
      = submit_tag t(".submit"), class: "btn btn-info", style: "margin-top: 25px;width: 100%;"

- unless flash[:error].present?

  = column_chart @data

  .table-responsive
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th= t(".type")
          %th= t(".count")

      %tbody
        - @data.each do |key, value|
          %tr
            %td= key
            %td= value

  .row
    .col-xs-6
      %h4= t(".adopted_ratio", total: @adoption_total, adopted: @adopted_total)
      - if @adopted_total > 0
        %h3= t(".average_adoption_time")
        %h4= average_time(@avg_adoption_time)

    .col-xs-6
      %h4= t(".found_ratio", total: @lost_total, found: @found_total)
      - if @found_total > 0
        %h3= t(".average_found_time")
        %h4= average_time(@avg_found_time)